# Generated by Django 5.2.6 on 2025-09-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('age', models.PositiveIntegerField()),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20)),
                ('saved', models.BooleanField(default=False, help_text='Ameokoka')),
                ('church_registration_number', models.CharField(max_length=50, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('center_area', models.CharField(max_length=100)),
                ('zone', models.CharField(max_length=100)),
                ('cell', models.CharField(max_length=100)),
                ('postal_address', models.TextField(blank=True)),
                ('mobile_no', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('church_position', models.CharField(blank=True, max_length=100)),
                ('visitors_count', models.PositiveIntegerField(default=0)),
                ('origin', models.CharField(choices=[('invited', 'Invited'), ('efatha', 'Efatha')], max_length=20)),
                ('residence', models.CharField(max_length=100)),
                ('career', models.CharField(blank=True, max_length=100)),
                ('attending_date', models.DateField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='member_pictures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
