# Generated by Django 5.2.6 on 2025-09-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_center_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='church_registration_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
