# Generated by Django 5.2.6 on 2025-09-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_make_church_registration_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
