# Generated by Django 5.2.6 on 2025-09-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('registrant', 'Registrant'), ('member', 'Member')], default='admin', max_length=20),
        ),
    ]
