# Generated by Django 5.2.6 on 2025-09-21 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(choices=[('members', 'Members'), ('analytics', 'Analytics'), ('users', 'User Activity'), ('financial', 'Financial')], max_length=20)),
                ('format', models.CharField(choices=[('csv', 'CSV'), ('excel', 'Excel'), ('pdf', 'PDF')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.CharField(max_length=50)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('filters_applied', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_by', 'created_at'], name='analytics_e_created_4f1247_idx'), models.Index(fields=['export_type', 'created_at'], name='analytics_e_export__95bf29_idx')],
            },
        ),
    ]
